export const EXAM_DATE = '2027-01-10';
export const START_DATE = '2026-09-23';
export const TOTAL_PLAN_HOURS = 218;

export const subjectMeta = {
  'Ética/OAB': { priority: 'A+', historical: 8.0, short: 'Ética', color: '#D6B56D' },
  'Constitucional': { priority: 'A', historical: 6.0, short: 'Const.', color: '#8CB4FF' },
  'Civil': { priority: 'A', historical: 6.0, short: 'Civil', color: '#A9D8B8' },
  'Processo Civil': { priority: 'A', historical: 6.0, short: 'Proc. Civil', color: '#A7C7E7' },
  'Penal': { priority: 'A', historical: 5.8, short: 'Penal', color: '#E7A7A7' },
  'Processo Penal': { priority: 'A', historical: 6.1, short: 'Proc. Penal', color: '#D7A7E7' },
  'Administrativo': { priority: 'A', historical: 5.3, short: 'Adm.', color: '#E7D3A7' },
  'Tributário': { priority: 'A', historical: 5.0, short: 'Trib.', color: '#A7D9E7' },
  'Trabalho': { priority: 'A', historical: 4.9, short: 'Trab.', color: '#F0B98B' },
  'Processo do Trabalho': { priority: 'A', historical: 5.1, short: 'Proc. Trab.', color: '#CFB0E8' },
  'Empresarial': { priority: 'B', historical: 4.0, short: 'Emp.', color: '#B7D7A8' },
  'Consumidor': { priority: 'C', historical: 2.0, short: 'CDC', color: '#F5C6AA' },
  'ECA': { priority: 'C', historical: 2.0, short: 'ECA', color: '#F6D7A7' },
  'Direitos Humanos': { priority: 'C', historical: 2.0, short: 'DH', color: '#B9D5F5' },
  'Filosofia': { priority: 'C', historical: 2.0, short: 'Filosofia', color: '#D7C7F5' },
  'Ambiental': { priority: 'C', historical: 2.0, short: 'Ambiental', color: '#A8DDB5' },
  'Financeiro': { priority: 'C', historical: 2.0, short: 'Financeiro', color: '#F2CF7D' },
  'Eleitoral': { priority: 'C', historical: 2.0, short: 'Eleitoral', color: '#BCD6F2' },
  'Previdenciário': { priority: 'C', historical: 2.0, short: 'Prev.', color: '#E5B8D6' },
  'Internacional': { priority: 'C', historical: 2.0, short: 'Intern.', color: '#B9CDE5' },
  'Misto': { priority: '—', historical: 0, short: 'Misto', color: '#CBD5E1' },
  'Simulado': { priority: '—', historical: 0, short: 'Simulado', color: '#F8D477' },
};

const B = (subject, topic, law = '', questions = 8, mode = 'Estudo dirigido') => ({ subject, topic, law, questions, mode });
const D = (date, a, b, phase = 'Base', note = '') => ({ date, blocks: [a, b], phase, note });

export const studyPlan = [
  D('2026-09-23', B('Ética/OAB','Atividades privativas e prerrogativas do advogado','Lei 8.906/94, arts. 1º–7º',8), B('Constitucional','Controle de constitucionalidade: fundamentos; difuso × concentrado','CF + Lei 9.868/99 (visão geral)',8)),
  D('2026-09-24', B('Civil','Pessoa natural e jurídica; personalidade e capacidade','CC, arts. 1º–69',8), B('Processo Civil','Jurisdição e competência','CPC, arts. 16–69',8)),
  D('2026-09-25', B('Penal','Princípios e aplicação da lei penal','CP, arts. 1º–12',8), B('Processo Penal','Inquérito policial','CPP, arts. 4º–23',8)),
  D('2026-09-26', B('Administrativo','Princípios e organização administrativa','CF, art. 37 + organização administrativa',8), B('Tributário','Competência tributária','CF, arts. 145–162 + CTN',8)),
  D('2026-09-27', B('Trabalho','Relação de emprego: empregado, empregador e requisitos','CLT, arts. 2º–6º',8), B('Processo do Trabalho','Competência da Justiça do Trabalho','CF, art. 114 + CLT',8)),
  D('2026-09-28', B('Ética/OAB','Inscrição e exercício profissional','Lei 8.906/94, arts. 8º–14',10), B('Empresarial','Empresário e registro','CC, arts. 966–980',8)),
  D('2026-09-29', B('Financeiro','PPA, LDO e LOA; estrutura orçamentária','CF, arts. 165–169',8), B('Misto','Questões cumulativas da semana','20–25 questões FGV',20,'Recuperação ativa'), 'Base', 'Primeiro fechamento semanal: corrija profundamente, não corra por volume.'),

  D('2026-09-30', B('Ética/OAB','Incompatibilidades e impedimentos','Lei 8.906/94, arts. 27–30',10), B('Constitucional','ADI, ADC, ADPF e ADO','CF + Leis 9.868/99 e 9.882/99',8)),
  D('2026-10-01', B('Civil','Negócio jurídico: validade, defeitos e invalidade','CC, arts. 104–184',8), B('Processo Civil','Partes, procuradores e atos processuais','CPC, arts. 70–293',8)),
  D('2026-10-02', B('Penal','Fato típico, resultado, nexo causal e tipicidade','CP, arts. 13–25',8), B('Processo Penal','Ação penal','CPP, arts. 24–62',8)),
  D('2026-10-03', B('Administrativo','Atos administrativos','Atributos, elementos, invalidação e convalidação',8), B('Tributário','Imunidades e limitações ao poder de tributar','CF, arts. 150–152',8)),
  D('2026-10-04', B('Trabalho','Contrato de trabalho','CLT: formação, modalidades e alterações',8), B('Processo do Trabalho','Reclamação trabalhista e audiência','CLT, arts. 840–850',8)),
  D('2026-10-05', B('Ética/OAB','Sociedade de advogados','Lei 8.906/94, arts. 15–17 + Regulamento',10), B('Empresarial','Estabelecimento e nome empresarial','CC, arts. 1.142–1.168',8)),
  D('2026-10-06', B('Consumidor','Fato do produto/serviço × vício','CDC, arts. 12–27',8), B('Misto','Questões cumulativas dos últimos 7 dias','20–25 questões FGV',20,'Recuperação ativa')),

  D('2026-10-07', B('Ética/OAB','Honorários advocatícios','Lei 8.906/94 + CED',10), B('Constitucional','Direitos fundamentais e remédios constitucionais','CF, art. 5º',8)),
  D('2026-10-08', B('Civil','Prescrição × decadência','CC, arts. 189–211',8), B('Processo Civil','Tutela provisória','CPC, arts. 294–311',8)),
  D('2026-10-09', B('Penal','Dolo, culpa, erro de tipo e erro de proibição','CP, arts. 18–21',8), B('Processo Penal','Competência penal','CPP, arts. 69–91',8)),
  D('2026-10-10', B('Administrativo','Agentes públicos','CF, arts. 37–41',8), B('Tributário','Espécies tributárias','CF + CTN',8)),
  D('2026-10-11', B('Trabalho','Salário e remuneração','CLT, arts. 457–467',8), B('Processo do Trabalho','Provas, revelia e confissão','CLT + CPC subsidiário',8)),
  D('2026-10-12', B('Ética/OAB','Publicidade profissional','CED + Provimento 205/2021',10), B('Empresarial','Sociedades: fundamentos e limitada','CC, arts. 981–1.087',8)),
  D('2026-10-13', B('ECA','Direitos fundamentais; proteção integral','ECA, arts. 1º–24',8), B('Misto','Questões cumulativas da semana','20–25 questões FGV',20,'Recuperação ativa')),

  D('2026-10-14', B('Ética/OAB','Sigilo, mandato e relação advogado-cliente','CED + Estatuto',10), B('Constitucional','Federação e repartição de competências','CF, arts. 18–43',8)),
  D('2026-10-15', B('Civil','Obrigações: modalidades, adimplemento e inadimplemento','CC, arts. 233–420',8), B('Processo Civil','Procedimento comum: petição, defesa e saneamento','CPC, arts. 318–357',8)),
  D('2026-10-16', B('Penal','Ilicitude e culpabilidade','CP, arts. 23–28',8), B('Processo Penal','Provas: princípios, sistemas e espécies','CPP, arts. 155–250',8)),
  D('2026-10-17', B('Administrativo','Serviços públicos e delegação','CF, art. 175 + Lei 8.987/95',8), B('Tributário','Obrigação e responsabilidade tributária','CTN, arts. 113–138',8)),
  D('2026-10-18', B('Trabalho','Jornada, horas extras, intervalos e repouso','CLT, arts. 58–75',8), B('Processo do Trabalho','Recursos trabalhistas I','CLT, arts. 893–901',8)),
  D('2026-10-19', B('Ética/OAB','Infrações disciplinares','Lei 8.906/94, art. 34',10), B('Empresarial','Sociedades: responsabilidade dos sócios e administração','CC + sociedades',8)),
  D('2026-10-20', B('Direitos Humanos','Sistema global e sistema interamericano','CF + CADH',8), B('Misto','Questões cumulativas da semana','20–25 questões FGV',20,'Recuperação ativa')),

  D('2026-10-21', B('Ética/OAB','Sanções disciplinares','Lei 8.906/94, arts. 35–43',10), B('Constitucional','Poder Legislativo e processo legislativo','CF, arts. 44–75',8)),
  D('2026-10-22', B('Civil','Contratos: princípios, formação, revisão e extinção','CC, arts. 421–480',8), B('Processo Civil','Provas','CPC, arts. 369–484',8)),
  D('2026-10-23', B('Penal','Tentativa, desistência, arrependimento e crime impossível','CP, arts. 14–17',8), B('Processo Penal','Provas ilícitas, reconhecimento e cadeia de custódia','CPP, arts. 157 e 158-A–158-F',8)),
  D('2026-10-24', B('Administrativo','Responsabilidade civil do Estado','CF, art. 37, §6º + jurisprudência consolidada',8), B('Tributário','Crédito tributário e lançamento','CTN, arts. 139–150',8)),
  D('2026-10-25', B('Trabalho','Férias e repousos','CLT, arts. 129–153',8), B('Processo do Trabalho','Recursos trabalhistas II','CLT + súmulas essenciais',8)),
  D('2026-10-26', B('Ética/OAB','Processo disciplinar I','Lei 8.906/94 + CED',10), B('Empresarial','Sociedade anônima: noções essenciais','Lei 6.404/76',8)),
  D('2026-10-27', B('Filosofia','Jusnaturalismo, positivismo e interpretação','Conceitos centrais + questões FGV',8), B('Misto','Questões cumulativas da semana','20–25 questões FGV',20,'Recuperação ativa')),

  D('2026-10-28', B('Ética/OAB','Processo disciplinar II e prescrição','Estatuto + CED',10), B('Constitucional','Poder Executivo, Judiciário e funções essenciais','CF, arts. 76–135',8)),
  D('2026-10-29', B('Civil','Responsabilidade civil','CC, arts. 186–188 e 927–954',8), B('Processo Civil','Sentença e coisa julgada','CPC, arts. 485–508',8)),
  D('2026-10-30', B('Penal','Concurso de pessoas e concurso de crimes','CP, arts. 29–31 e 69–76',8), B('Processo Penal','Prisões e medidas cautelares','CPP, arts. 282–350',8)),
  D('2026-10-31', B('Administrativo','Intervenção do Estado na propriedade','Desapropriação, requisição e limitações',8), B('Tributário','Suspensão, extinção e exclusão do crédito','CTN, arts. 151–182',8)),
  D('2026-11-01', B('Trabalho','Extinção do contrato e justa causa','CLT, arts. 477–486',8), B('Processo do Trabalho','Liquidação e execução I','CLT, arts. 876–892',8)),
  D('2026-11-02', B('Ética/OAB','Prerrogativas: revisão por questões avançadas','Lei 8.906/94, art. 7º',12,'Questões dirigidas'), B('Empresarial','Títulos de crédito: princípios e espécies','CC + legislação especial',8)),
  D('2026-11-03', B('Ambiental','Competências, licenciamento e responsabilidade','CF, art. 225 + legislação ambiental',8), B('Misto','Questões cumulativas da semana','20–25 questões FGV',20,'Recuperação ativa')),

  D('2026-11-04', B('Ética/OAB','Infrações e sanções: revisão ativa','Estatuto, arts. 34–43',12,'Questões dirigidas'), B('Constitucional','Funções essenciais à Justiça e controle: revisão','CF, arts. 127–135 + controle',8)),
  D('2026-11-05', B('Civil','Posse e propriedade','CC, arts. 1.196–1.276',8), B('Processo Civil','Cumprimento de sentença','CPC, arts. 513–538',8)),
  D('2026-11-06', B('Penal','Penas e dosimetria','CP, arts. 32–76',8), B('Processo Penal','Procedimentos e Tribunal do Júri','CPP, arts. 394–497',8)),
  D('2026-11-07', B('Administrativo','Lei 14.133: princípios, agentes e modalidades','Lei 14.133/2021',8), B('Tributário','Impostos: competências e características','CF + CTN',8)),
  D('2026-11-08', B('Trabalho','Estabilidade e garantias provisórias','CLT + ADCT + jurisprudência consolidada',8), B('Processo do Trabalho','Liquidação e execução II','CLT, arts. 876–892',8)),
  D('2026-11-09', B('Ética/OAB','Questões dirigidas: bloco geral','Estatuto + CED',15,'Questões dirigidas'), B('Empresarial','Recuperação judicial','Lei 11.101/2005',8)),
  D('2026-11-10', B('Eleitoral','Direitos políticos, elegibilidade e inelegibilidades','CF + LC 64/90',8), B('Misto','Questões cumulativas da semana','20–25 questões FGV',20,'Recuperação ativa')),

  D('2026-11-11', B('Ética/OAB','Prerrogativas: bateria avançada','Estatuto, arts. 6º–7º',15,'Questões dirigidas'), B('Constitucional','Controle de constitucionalidade: bateria avançada','ADI/ADC/ADPF/ADO',10,'Questões dirigidas')),
  D('2026-11-12', B('Civil','Família: casamento, união estável e regimes','CC, Direito de Família',8), B('Processo Civil','Execução: títulos, penhora e defesa','CPC, arts. 771–925',8)),
  D('2026-11-13', B('Penal','Crimes contra pessoa e patrimônio','CP, Parte Especial',8), B('Processo Penal','Recursos e habeas corpus','CPP + CF',8)),
  D('2026-11-14', B('Administrativo','Lei 14.133: contratação direta e contratos','Lei 14.133/2021',8), B('Tributário','Administração e processo tributário','CTN + execução fiscal',8)),
  D('2026-11-15', B('Trabalho','FGTS e temas correlatos','Lei 8.036/90 + CLT',8), B('Processo do Trabalho','Procedimentos especiais','CLT + legislação',8)),
  D('2026-11-16', B('Ética/OAB','Disciplina: questões de alta recorrência','Infrações, sanções e processo',15,'Questões dirigidas'), B('Empresarial','Falência','Lei 11.101/2005',8)),
  D('2026-11-17', B('Previdenciário','Segurados e benefícios por incapacidade','Lei 8.213/91',8), B('Misto','Questões cumulativas da semana','20–25 questões FGV',20,'Recuperação ativa')),

  D('2026-11-18', B('Ética/OAB','Honorários e publicidade: revisão por questões','Estatuto + CED + Prov. 205/2021',15,'Questões dirigidas'), B('Constitucional','Direitos fundamentais: revisão por questões','CF, art. 5º',10,'Questões dirigidas')),
  D('2026-11-19', B('Civil','Sucessões','CC, arts. 1.784–2.027',8), B('Processo Civil','Recursos','CPC, arts. 994–1.044',8)),
  D('2026-11-20', B('Penal','Crimes contra a Administração Pública','CP, arts. 312–359-H',8), B('Processo Penal','Provas e prisões: revisão de alta incidência','CPP',10,'Questões dirigidas')),
  D('2026-11-21', B('Administrativo','Improbidade administrativa','Lei 8.429/92, redação atual',8), B('Tributário','Competência e imunidades: revisão','CF + CTN',10,'Questões dirigidas')),
  D('2026-11-22', B('Trabalho','Direito coletivo do trabalho','CLT + CF',8), B('Processo do Trabalho','Competência e recursos: revisão','CLT + CF',10,'Questões dirigidas')),
  D('2026-11-23', B('Ética/OAB','Questões mistas de Ética','Estatuto + Regulamento + CED',15,'Questões dirigidas'), B('Empresarial','Propriedade industrial','Lei 9.279/96',8)),
  D('2026-11-24', B('Internacional','Nacionalidade, extradição e tratados','CF + DIP/Direito Internacional',8), B('Misto','Questões cumulativas: fechamento da base','25 questões FGV',25,'Recuperação ativa'), 'Fechamento da base', 'Ao terminar hoje, todas as disciplinas já tiveram contato estruturado.'),

  D('2026-11-25', B('Ética/OAB','Questões FGV: Ética completa','20 questões selecionadas',10,'Questões + correção'), B('Constitucional','Questões FGV: controle + direitos + poderes','20 questões selecionadas',10,'Questões + correção'), 'Consolidação'),
  D('2026-11-26', B('Civil','Questões FGV: parte geral + reais + família','20 questões selecionadas',10,'Questões + correção'), B('Processo Civil','Questões FGV: execução + procedimento + recursos','20 questões selecionadas',10,'Questões + correção'), 'Consolidação'),
  D('2026-11-27', B('Penal','Questões FGV: teoria do crime + penas','20 questões selecionadas',10,'Questões + correção'), B('Processo Penal','Questões FGV: inquérito + provas + prisões','20 questões selecionadas',10,'Questões + correção'), 'Consolidação'),
  D('2026-11-28', B('Administrativo','Questões FGV: licitações + atos + agentes','20 questões selecionadas',10,'Questões + correção'), B('Tributário','Questões FGV: competência + crédito + espécies','20 questões selecionadas',10,'Questões + correção'), 'Consolidação'),
  D('2026-11-29', B('Trabalho','Questões FGV: jornada + extinção + estabilidade','20 questões selecionadas',10,'Questões + correção'), B('Processo do Trabalho','Questões FGV: procedimento + recursos + execução','20 questões selecionadas',10,'Questões + correção'), 'Consolidação'),
  D('2026-11-30', B('Ética/OAB','Questões FGV: pontos fracos identificados','Caderno de erros',10,'Questões adaptativas'), B('Empresarial','Questões FGV: sociedades + RJ/falência','20 questões selecionadas',10,'Questões + correção'), 'Consolidação'),
  D('2026-12-01', B('Financeiro','Questões FGV: orçamento + LRF','15 questões selecionadas',8,'Questões + correção'), B('Misto','Mini-simulado cumulativo','20 questões mistas',20,'Mini-simulado'), 'Consolidação'),
  D('2026-12-02', B('Ética/OAB','Questões FGV: Ética completa II','20 questões selecionadas',10,'Questões + correção'), B('Constitucional','Questões FGV: Constitucional II','20 questões selecionadas',10,'Questões + correção'), 'Consolidação'),
  D('2026-12-03', B('Civil','Questões FGV: Civil II','20 questões selecionadas',10,'Questões + correção'), B('Processo Civil','Questões FGV: Processo Civil II','20 questões selecionadas',10,'Questões + correção'), 'Consolidação'),
  D('2026-12-04', B('Penal','Questões FGV: Penal II','20 questões selecionadas',10,'Questões + correção'), B('Processo Penal','Questões FGV: Processo Penal II','20 questões selecionadas',10,'Questões + correção'), 'Consolidação'),
  D('2026-12-05', B('Administrativo','Questões FGV: Administrativo II','20 questões selecionadas',10,'Questões + correção'), B('Tributário','Questões FGV: Tributário II','20 questões selecionadas',10,'Questões + correção'), 'Consolidação'),
  D('2026-12-06', B('Trabalho','Questões FGV: Trabalho II','20 questões selecionadas',10,'Questões + correção'), B('Processo do Trabalho','Questões FGV: Processo do Trabalho II','20 questões selecionadas',10,'Questões + correção'), 'Consolidação'),
  D('2026-12-07', B('Ética/OAB','Questões FGV: Ética pelos erros','Caderno de erros',10,'Questões adaptativas'), B('Empresarial','Questões FGV: Empresarial II','20 questões selecionadas',10,'Questões + correção'), 'Consolidação'),
  D('2026-12-08', B('Consumidor','Questões FGV: CDC de maior incidência','Vício/fato + práticas comerciais',8,'Questões + correção'), B('Misto','Mini-simulado cumulativo','25 questões mistas',25,'Mini-simulado'), 'Consolidação'),

  D('2026-12-09', B('Misto','25 questões intercaladas: Ética + Constitucional + Administrativo','FGV/OAB',13,'Interleaving'), B('Misto','Correção por fundamento legal + caderno de erros','Somente lacunas detectadas',12,'Correção ativa'), 'Interleaving'),
  D('2026-12-10', B('Misto','25 questões intercaladas: Civil + Processo Civil + Empresarial','FGV/OAB',13,'Interleaving'), B('Misto','Correção por fundamento legal + caderno de erros','Somente lacunas detectadas',12,'Correção ativa'), 'Interleaving'),
  D('2026-12-11', B('Misto','25 questões intercaladas: Penal + Processo Penal','FGV/OAB',13,'Interleaving'), B('Misto','Correção por fundamento legal + caderno de erros','Somente lacunas detectadas',12,'Correção ativa'), 'Interleaving'),
  D('2026-12-12', B('Misto','25 questões intercaladas: Trabalho + Processo do Trabalho','FGV/OAB',13,'Interleaving'), B('Misto','Correção por fundamento legal + caderno de erros','Somente lacunas detectadas',12,'Correção ativa'), 'Interleaving'),
  D('2026-12-13', B('Misto','25 questões intercaladas: Tributário + Administrativo + Financeiro','FGV/OAB',13,'Interleaving'), B('Misto','Correção por fundamento legal + caderno de erros','Somente lacunas detectadas',12,'Correção ativa'), 'Interleaving'),
  D('2026-12-14', B('Misto','25 questões intercaladas: matérias menores','FGV/OAB',13,'Interleaving'), B('Misto','Correção por fundamento legal + mapa de fraquezas','Somente lacunas detectadas',12,'Correção ativa'), 'Interleaving'),
  D('2026-12-15', B('Misto','25 questões aleatórias de todas as disciplinas','FGV/OAB',25,'Mini-simulado'), B('Misto','Correção profunda das 5 questões mais difíceis','Caderno de erros',0,'Correção ativa'), 'Interleaving'),
  D('2026-12-16', B('Misto','25 questões: núcleo A — rodada 2','Ética, Const., Civil, CPC',13,'Interleaving'), B('Misto','Correção e lei seca dos erros','Caderno de erros',12,'Correção ativa'), 'Interleaving'),
  D('2026-12-17', B('Misto','25 questões: núcleo A — rodada 2','Penal, CPP, Adm., Tributário',13,'Interleaving'), B('Misto','Correção e lei seca dos erros','Caderno de erros',12,'Correção ativa'), 'Interleaving'),
  D('2026-12-18', B('Misto','25 questões: Trabalho + Proc. Trabalho + Empresarial','FGV/OAB',13,'Interleaving'), B('Misto','Correção e lei seca dos erros','Caderno de erros',12,'Correção ativa'), 'Interleaving'),
  D('2026-12-19', B('Misto','25 questões: matérias menores — rodada 2','FGV/OAB',13,'Interleaving'), B('Misto','Correção e lei seca dos erros','Caderno de erros',12,'Correção ativa'), 'Interleaving'),
  D('2026-12-20', B('Misto','25 questões: assuntos vermelhos do caderno','Seus piores temas',13,'Interleaving'), B('Misto','Correção e reclassificação das fraquezas','Caderno de erros',12,'Correção ativa'), 'Interleaving'),
  D('2026-12-21', B('Misto','30 questões aleatórias — ritmo de prova','FGV/OAB',30,'Mini-simulado'), B('Misto','Correção objetiva; identificar 3 lacunas','Caderno de erros',0,'Correção ativa'), 'Interleaving'),
  D('2026-12-22', B('Ética/OAB','Revisão de alto retorno: Estatuto + CED','Lei seca marcada + 15 questões',15,'Revisão ativa'), B('Misto','Revisão dos 10 erros mais recorrentes','Caderno de erros',0,'Recuperação ativa'), 'Interleaving'),

  D('2026-12-23', B('Ética/OAB','Revisão final estruturada: prerrogativas + disciplina','Lei 8.906/94',12,'Revisão de alto retorno'), B('Constitucional','Controle + direitos fundamentais','CF',10,'Revisão de alto retorno'), 'Reta final'),
  D('2026-12-24', B('Consumidor','Vício/fato + práticas comerciais','CDC',10,'Revisão de alto retorno'), B('ECA','Direitos fundamentais + medidas','ECA',10,'Revisão de alto retorno'), 'Reta final'),
  D('2026-12-25', B('Direitos Humanos','Sistema interamericano + tratados','CADH + CF',10,'Revisão de alto retorno'), B('Filosofia','Positivismo, jusnaturalismo e interpretação','Questões FGV',10,'Revisão de alto retorno'), 'Reta final'),
  D('2026-12-26', B('Ambiental','Responsabilidade + licenciamento + competências','CF, art. 225',10,'Revisão de alto retorno'), B('Financeiro','PPA/LDO/LOA + LRF','CF + LRF',10,'Revisão de alto retorno'), 'Reta final'),
  D('2026-12-27', B('Eleitoral','Elegibilidade + inelegibilidades + partidos','CF + LC 64/90',10,'Revisão de alto retorno'), B('Previdenciário','Segurados + benefícios por incapacidade','Lei 8.213/91',10,'Revisão de alto retorno'), 'Reta final'),
  D('2026-12-28', B('Internacional','Nacionalidade + extradição + tratados','CF + DIP',10,'Revisão de alto retorno'), B('Empresarial','Sociedades + recuperação/falência','CC + Lei 11.101/05',10,'Revisão de alto retorno'), 'Reta final'),
  D('2026-12-29', B('Misto','30 questões completamente mistas','FGV/OAB',30,'Mini-simulado'), B('Misto','Correção + mapa das 5 últimas fraquezas','Caderno de erros',0,'Correção ativa'), 'Reta final'),

  D('2026-12-30', B('Simulado','OAB 46 — questões 1–10','Prova original',10,'Simulado fracionado'), B('Simulado','OAB 46 — questões 11–20 + correção','Prova original',10,'Simulado fracionado'), 'Simulados'),
  D('2026-12-31', B('Simulado','OAB 46 — questões 21–30','Prova original',10,'Simulado fracionado'), B('Simulado','OAB 46 — questões 31–40 + correção','Prova original',10,'Simulado fracionado'), 'Simulados'),
  D('2027-01-01', B('Simulado','OAB 46 — questões 41–50','Prova original',10,'Simulado fracionado'), B('Simulado','OAB 46 — questões 51–60 + correção','Prova original',10,'Simulado fracionado'), 'Simulados'),
  D('2027-01-02', B('Simulado','OAB 46 — questões 61–70','Prova original',10,'Simulado fracionado'), B('Simulado','OAB 46 — questões 71–80 + fechar resultado /80','Meta operacional: 50+',10,'Simulado fracionado'), 'Simulados'),
  D('2027-01-03', B('Simulado','OAB 47 — questões 1–10','Prova original',10,'Simulado fracionado'), B('Simulado','OAB 47 — questões 11–20 + correção','Prova original',10,'Simulado fracionado'), 'Simulados'),
  D('2027-01-04', B('Simulado','OAB 47 — questões 21–30','Prova original',10,'Simulado fracionado'), B('Simulado','OAB 47 — questões 31–40 + correção','Prova original',10,'Simulado fracionado'), 'Simulados'),
  D('2027-01-05', B('Simulado','OAB 47 — questões 41–50','Prova original',10,'Simulado fracionado'), B('Simulado','OAB 47 — questões 51–60 + correção','Prova original',10,'Simulado fracionado'), 'Simulados'),
  D('2027-01-06', B('Simulado','OAB 47 — questões 61–70','Prova original',10,'Simulado fracionado'), B('Simulado','OAB 47 — questões 71–80 + fechar resultado /80','Meta operacional: 50+',10,'Simulado fracionado'), 'Simulados'),
  D('2027-01-07', B('Ética/OAB','Revisão dos erros finais de Ética','Caderno de erros + Estatuto',10,'Revisão final'), B('Misto','Constitucional + Administrativo + Tributário: erros finais','Somente pontos frágeis',10,'Revisão final'), 'Revisão final'),
  D('2027-01-08', B('Misto','Civil + CPC + Empresarial: erros finais','Somente pontos frágeis',10,'Revisão final'), B('Misto','Penal + CPP + Trabalho + Proc. Trabalho: erros finais','Somente pontos frágeis',10,'Revisão final'), 'Revisão final'),
  D('2027-01-09', B('Ética/OAB','Lei seca marcada + caderno de erros','Sem conteúdo novo',8,'Revisão leve'), B('Misto','Preparação de prova: logística + leitura leve','Nada de maratona',0,'Descompressão'), 'Véspera', 'Sem conteúdo novo. O objetivo hoje é chegar cognitivamente inteiro à prova.'),
];

export const phaseDescriptions = {
  'Base': 'Construção do núcleo de pontuação com teoria enxuta, lei seca e questões no mesmo dia.',
  'Fechamento da base': 'Todas as disciplinas já foram visitadas; a partir daqui a teoria deixa de ser protagonista.',
  'Consolidação': 'Predomínio de questões FGV, correção e retorno aos pontos fracos.',
  'Interleaving': 'Questões misturadas para treinar identificação do instituto sem pista da matéria.',
  'Reta final': 'Revisão de alto retorno e captura dos pontos das matérias menores.',
  'Simulados': 'Provas recentes preservadas para aferição quase cega do desempenho.',
  'Revisão final': 'Somente erros, lei seca marcada e assuntos já estudados.',
  'Véspera': 'Baixa carga cognitiva; nada de conteúdo novo.',
};

export const reviewIntervals = [1, 3, 7, 14, 30];
